name: Test
on: 
  workflow_dispatch:
  pull_request:

jobs:
  Testingggggggg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ... your other steps ...

      - name: Wait for manual approval
        uses: ./.github/actions/manual-approval
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          approval_command: '/approve'
          # approvers: 'octocat,anotheruser'

      - name: Run Deploy script file
        run: echo "Deploying..."
