on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'GitHub Issue number to watch for approval'
        required: true

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for manual approval
        uses: ./.github/actions/manual-approval
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.inputs.issue_number }}
          approval_command: '/approve'

      - name: Run Deploy script file
        run: echo "Deploying..."
